# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.IntegerField(default=0)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=25)),
                ('visitorFirstName', models.CharField(max_length=25)),
                ('visitorLastName', models.CharField(max_length=25)),
                ('dateRequested', models.DateTimeField(auto_now_add=True, verbose_name='Date Requested')),
                ('expectedArrivalDate', models.DateTimeField(null=True, verbose_name='Expected Arrival Date')),
                ('approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=8)),
                ('purposeVisit', models.CharField(max_length=1000)),
                ('approvalTime', models.DateTimeField(null=True, verbose_name='Approval Time')),
                ('numGuests', models.IntegerField(default=1)),
                ('photo', models.ImageField(upload_to='')),
                ('specialRequest', models.BooleanField()),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ADMIN', to='login.Profile')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GUARD', to='login.Profile')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
    ]
