# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestsPerVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('CNIC', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedGuests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRequested', models.DateTimeField(auto_now_add=True, verbose_name='Date Requested')),
                ('expectedArrivalDate', models.DateTimeField(null=True, verbose_name='Expected Arrival Date')),
                ('approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=8)),
                ('approvalTime', models.DateTimeField(null=True, verbose_name='Approval Time')),
                ('numGuests', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitDate', models.DateTimeField(auto_now_add=True, verbose_name='Visit Date')),
                ('entryTime', models.DateTimeField(auto_now_add=True, verbose_name='Entry Time')),
                ('exitTime', models.DateTimeField(null=True, verbose_name='Exit Time')),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Requests')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.Person')),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('login.person',),
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.Person')),
            ],
            bases=('login.person',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.Person')),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('login.person',),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='login.Person')),
            ],
            bases=('login.person',),
        ),
        migrations.AddField(
            model_name='requestedguests',
            name='requestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Requests'),
        ),
        migrations.AddField(
            model_name='guestspervisit',
            name='visitID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Visit'),
        ),
        migrations.AddField(
            model_name='requests',
            name='adminID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Admin'),
        ),
        migrations.AddField(
            model_name='requests',
            name='hostID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Host'),
        ),
        migrations.AddField(
            model_name='requestedguests',
            name='visitorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Visitor'),
        ),
        migrations.AddField(
            model_name='guestspervisit',
            name='guardID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Guard'),
        ),
        migrations.AddField(
            model_name='guestspervisit',
            name='visitorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Visitor'),
        ),
    ]
