# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestsPerVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.IntegerField(default=0)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedGuests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRequested', models.DateTimeField(auto_now_add=True, verbose_name='Date Requested')),
                ('expectedArrivalDate', models.DateTimeField(blank=True, null=True, verbose_name='Expected Arrival Date')),
                ('approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=8)),
                ('approvalTime', models.DateTimeField(blank=True, null=True, verbose_name='Approval Time')),
                ('purposeVisit', models.CharField(max_length=1000)),
                ('numGuests', models.IntegerField(default=1)),
                ('photo', models.ImageField(upload_to='')),
                ('specialRequest', models.BooleanField()),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ADMIN', to='login.Profile')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryTime', models.DateTimeField(blank=True, null=True)),
                ('exitTime', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Requests')),
            ],
        ),
        migrations.AddField(
            model_name='requestedguests',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Requests'),
        ),
        migrations.AddField(
            model_name='requestedguests',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Visitor'),
        ),
        migrations.AddField(
            model_name='guestspervisit',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Guard', to='login.Profile'),
        ),
        migrations.AddField(
            model_name='guestspervisit',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Visits'),
        ),
        migrations.AddField(
            model_name='guestspervisit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Visitor'),
        ),
    ]
