# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedguests',
            name='request',
        ),
        migrations.RemoveField(
            model_name='requestedguests',
            name='visitor',
        ),
        migrations.DeleteModel(
            name='RequestedGuests',
        ),
    ]
