# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Requests'),
        ),
    ]
