# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170509_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='archived',
            field=models.IntegerField(default=0),
        ),
    ]
