# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170507_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedGuests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='requests',
            name='photo',
        ),
        migrations.AddField(
            model_name='requestedguests',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Requests'),
        ),
        migrations.AddField(
            model_name='requestedguests',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Visitor'),
        ),
    ]
